CREATE TABLE `channels`
(
  `id` INT NOT NULL AUTO_INCREMENT,
  `channel` VARCHAR(50) NOT NULL,
  PRIMARY KEY(`id`),
   KEY `id`
(`id`) USING BTREE

) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8